title: Working Copy_final_this_one
description: A blog on writing, design, and technology.
url: "https://blog.wptk.org"
baseurl: ""
timezone: America/New_York

permalink: /:year/:month/:title/

theme: null

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
